### PR TITLE
Zuul integration

### PR DESCRIPTION
**Pull request by gtema**
Closes: #117

### CODE REVIEW

**Comment by lego963** [comment]
Current info which was created by setup.py is located: https://pypi.org/project/delatore/0.4.7.dev2/

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by gtema** [comment]
recheck

**Comment by lego963** [comment]
recheck

**Comment by lego963** [comment]
recheck

**Comment by lego963** [comment]
merge

**Pull request merged**
